language:
  - cpp

sudo: false

dist: xenial

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty
    packages:
      - cmake
      - libeigen3-dev

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  # - ctest

notifications:
  email: false
